### ISSUE TITLE
I can install this

### ISSUE THREAD

**Issue by yotama9** [pft/gimpmode#4]
I tried to install the gimp-mode. Emacs 24 on Ubuntu 13.04. I downloaded the file using `git clone` and everything is at 

```
~/emacs.d/gimpbomde
```

I entered the `gimp-install.el` file and where ever I type C-x C-e I get this error

```
Debugger entered--Lisp error: (void-variable %S)
   eval(%S nil)
   eval-last-sexp-1(nil)
   eval-last-sexp(nil)
   call-interactively(eval-last-sexp nil nil)
```

Please help

**Comment by pft** [comment]
What do you mean with 'entered the gimp-install.el file'?

**Comment by yotama9** [comment]
I really can't say, it was more than three years ago, I can't recall what I had in my mind at the time, or why I even needed this module. sorry.

**Comment by pft** [comment]
OK. Thanks. I'll close the issue then. Sorry for not asking about it earlier.
